export default {
  SET_ACTIVE_TOOL: 'SET_ACTIVE_TOOL',
  ADD_FRAME: 'ADD_FRAME',
  SET_ACTIVE_FRAME: 'SET_ACTIVE_FRAME',
  CLONE_FRAME: 'CLONE_FRAME',
  DELETE_FRAME: 'DELETE_FRAME',
  SAVE_FRAME: 'SAVE_FRAME',
  SET_PREVIEW_FPS: 'SET_PREVIEW_FPS',
  SET_PRIMARY_COLOR: 'SET_PRIMARY_COLOR',
  SET_SECONDARY_COLOR: 'SET_SECONDARY_COLOR',
  SWAP_COLORS: 'SWAP_COLORS'
};